app/urls.py
from django.urls import path

from app import views

app_name='app'

urlpatterns=[
    path('specific_template/',views.specific_template,name='specific_template'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

import app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home,name='home'),
    path('index/',views.index,name='index'),

    path('app/',include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'home.html')

def index(request):
    return render(request,'index.html')

def specific_template(request):
    return render(request,'specific_template.html')

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>This Is Home html file </h1>

    <h1><a href="{% url 'index' %}">Click here to travel to index html page</a></h1>
    <h1><a href="{% url 'app:specific_template' %}">click here to travel to specific template file</a></h1>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>This Is Index html file </h1>

    <h1><a href="{% url 'home' %}">Click here to travel to Home html page</a></h1>
    <h1><a href="{% url 'app:specific_template' %}">Click here to navigate to specific template file</a></h1>
</body>
</html>

templates/specific_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>specific template</title>
</head>
<body>
    <h1>This is Specific template html file</h1>
    <h1><a href="{% url 'home' %}">click here to navigate to home page</a></h1>
    <h1><a href="{% url 'index' %}">click here to navigate to index page</a></h1>
    
</body>
</html>